/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ListaDeTarefaRepositorio;
import dao.PessoaRepositorio;
import dao.TarefaRepositorio;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ListaDeTarefa;
import model.Pessoa;
import model.Tarefa;

/**
 *
 * @author Zeke
 */
public class SystemLogs extends javax.swing.JFrame {

    /**
     * Creates new form SystemLogs
     *
     * @param main
     */
    public SystemLogs(Main main) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        enableMainFrameOnClose(main);
    }

    private void enableMainFrameOnClose(JFrame main) {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                main.setEnabled(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfConsultar = new javax.swing.JTextField();
        jbConsultar = new javax.swing.JButton();
        jcbClasses = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaConsole = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfConsultar.setToolTipText("Inserir Id");

        jbConsultar.setText("Consultar");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        jcbClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa", "Lista de Tarefa", "Tarefa" }));

        jtaConsole.setColumns(20);
        jtaConsole.setRows(5);
        jScrollPane1.setViewportView(jtaConsole);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultar)
                    .addComponent(jcbClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        jtaConsole.setText("");
        HashMap<Integer, ?> hashmap = new HashMap<>();
        if (jcbClasses.getSelectedItem().equals("Pessoa")) {
            hashmap = (HashMap<Integer, Pessoa>) (new PessoaRepositorio()).getHashInicial();
        }
        if (jcbClasses.getSelectedItem().equals("Lista de Tarefa")) {
            hashmap = (HashMap<Integer, ListaDeTarefa>) (new ListaDeTarefaRepositorio()).getHashInicial();
        }
        if (jcbClasses.getSelectedItem().equals("Tarefa")) {
            hashmap = (HashMap<Integer, Tarefa>) (new TarefaRepositorio()).getHashInicial();
        }
        if (jtfConsultar.getText().equals("")) {
            hashmap.forEach(
                    (key, value)
                    -> jtaConsole.append(value.toString() + "\n"));
            return;
        }
        try {
            int id = Integer.parseInt(jtfConsultar.getText());
            jtaConsole.append(hashmap.get(id).toString() + "\n");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jbConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JComboBox<String> jcbClasses;
    private javax.swing.JTextArea jtaConsole;
    private javax.swing.JTextField jtfConsultar;
    // End of variables declaration//GEN-END:variables
}
